### ISSUE TITLE
Validation accuracy metric 

### ISSUE THREAD

**Issue by alpoler** [euwern/proxynca_pp#5]
You mention that training is controlled with every epoch with recall @1 score but evaluation of nmi is discarded and validation is tracked by harmonic mean of recall @1 and nmi against stated in paper. Is this done delibaretely ?

**Comment by euwern** [comment]
NMI is set to 1 during validation training (eval_nmi=False); in other words, it is only controlled by R@1.
Therefore, the evaluation based on the harmonic mean is the same as the evaluation based on R@1 since NMI is set to 1. In my early experimental design, I choose to include NMI in the calculation, but since NMI is slow to compute and unstable, I have abandoned this evaluation choice during validation training.
